tech_capitalization_map = {
    "python": "Python",
    "java": "Java",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "c": "C",
    "c++": "C++",
    "c#": "C#",
    "go": "Go",
    "golang": "Go",
    "rust": "Rust",
    "ruby": "Ruby",
    "php": "PHP",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "scala": "Scala",
    "sql": "SQL",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "sqlite": "SQLite",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "cassandra": "Cassandra",
    "hbase": "HBase",
    "hdfs": "HDFS",
    "spark": "Spark",
    "hadoop": "Hadoop",
    "flink": "Flink",
    "airflow": "Airflow",
    "kafka": "Kafka",
    "zookeeper": "ZooKeeper",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "circleci": "CircleCI",
    "github actions": "GitHub Actions",
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "react": "React",
    "react.js": "React",
    "vue": "Vue.js",
    "vue.js": "Vue.js",
    "angular": "Angular",
    "next.js": "Next.js",
    "nuxt.js": "Nuxt.js",
    "svelte": "Svelte",
    "tailwind": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "django": "Django",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "express": "Express.js",
    "node": "Node.js",
    "node.js": "Node.js",
    "graphql": "GraphQL",
    "rest": "REST",
    "grpc": "gRPC",
    "html": "HTML",
    "css": "CSS",
    "sass": "Sass",
    "less": "Less",
    "pytorch": "PyTorch",
    "tensorflow": "TensorFlow",
    "keras": "Keras",
    "sklearn": "scikit-learn",
    "scikit-learn": "scikit-learn",
    "pandas": "pandas",
    "numpy": "NumPy",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "openai": "OpenAI",
    "llama": "LLaMA",
    "t5": "T5",
    "bert": "BERT",
    "gpt": "GPT",
    "huggingface": "Hugging Face",
    "aws": "AWS",
    "amazon web services": "AWS",
    "azure": "Azure",
    "gcp": "GCP",
    "google cloud": "GCP",
    "firebase": "Firebase",
    "heroku": "Heroku",
    "netlify": "Netlify",
    "vercel": "Vercel",
    "linux": "Linux",
    "unix": "Unix",
    "macos": "macOS",
    "windows": "Windows",
    "bash": "Bash",
    "powershell": "PowerShell",
    "shell": "Shell",
    "vim": "Vim",
    "neovim": "Neovim",
    "vscode": "VS Code",
    "intellij": "IntelliJ",
    "eclipse": "Eclipse",
    "xcode": "Xcode",
    "android studio": "Android Studio",
    "jupyter": "Jupyter Notebook",
    "notebook": "Jupyter Notebook",
    "tableau": "Tableau",
    "powerbi": "Power BI",
    "excel": "Excel",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "databricks": "Databricks",
    "looker": "Looker",
    "superset": "Apache Superset",
    "airbyte": "Airbyte",
    "dbt": "dbt",
    "mlflow": "MLflow",
    "kibana": "Kibana",
    "elasticsearch": "Elasticsearch",
    "prometheus": "Prometheus",
    "grafana": "Grafana"
}

